### ISSUE TITLE
ChatBedrockConverse response not streaming

### ISSUE THREAD

**Issue by gituser022** [shiv248/Streamlit-x-LangGraph-Cookbooks#3]
Hi Shivanshu,

I have tried the simple streaming use-case and replaced just with bedrock FM instead of open AI , when I tried to run streamlit, I see following issues 

1) its not streaming but gathers all response
2) response from assistant is saved to streamlit state but not printed until there is a new user prompt. It can be simply fixed, not an issue but if it is fixed in repo, it will be helpful to others.

I have attached files.

Thanks

[Archive.zip](https://github.com/user-attachments/files/17509125/Archive.zip)

**Comment by shiv248** [comment]
ah @gituser022 as we predicted it is an issue with `ChatBedrockConverse` not with the streamlit components, I just tested with chatfireworks and chatopenai.

from a quick search try adding `streaming=True` to the params. the issue was brought up in the [`langchain-aws`](https://github.com/langchain-ai/langchain-aws) repo. 
I would recommend forwarding any further issues to the threads below, they are better suited to help you.
https://github.com/langchain-ai/langchain-aws/issues/217
https://github.com/langchain-ai/langchain-aws/pull/241
